export const meetings = [
  {
    id: 1,
    category: "캠핑",
    name: "캠핑처치",
    location: "서울",
    meetingDay: "격주 토~일",
    fee: "월 100,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/campchurch.jpg",
  },
  {
    id: 2,
    category: "캠핑",
    name: "캠핑클럽",
    location: "서울",
    meetingDay: "매주 토요일",
    fee: "월 10,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/campclub.jpg",
  },
  {
    id: 3,
    category: "캠핑",
    name: "캠핑라인",
    location: "인천",
    meetingDay: "매주 토요일",
    fee: "없음",
    thumbnail: "https://gi.esmplus.com/jjumang/campline.jpg",
  },
  {
    id: 4,
    category: "캠핑",
    name: "캠핑데칼",
    location: "수원",
    meetingDay: "매주 토요일",
    fee: "월 20,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/dekal.jpg",
  },
  {
    id: 5,
    category: "캠핑",
    name: "긴세상클럽",
    location: "부산",
    meetingDay: "매주 토요일",
    fee: "월 30,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/kinsesang.jpg",
  },
  {
    id: 6,
    category: "캠핑",
    name: "어반브러쉬",
    location: "부산",
    meetingDay: "매주 토요일",
    fee: "월 30,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/urbanbrush.jpg",
  },

  {
    id: 1,
    category: "야구",
    name: "블루드래곤",
    location: "서울",
    meetingDay: "매주 토요일",
    fee: "월 20,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballa_1.jpg",
  },
  {
    id: 2,
    category: "야구",
    name: "아스트로",
    location: "서울",
    meetingDay: "매주 토요일",
    fee: "월 10,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballa_2.jpg",
  },
  {
    id: 3,
    category: "야구",
    name: "LPB",
    location: "인천",
    meetingDay: "매주 토요일",
    fee: "없음",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballa_3.jpg",
  },
  {
    id: 4,
    category: "야구",
    name: "몬스터야구단",
    location: "수원",
    meetingDay: "매주 토요일",
    fee: "월 20,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballa_4.jpg",
  },
  {
    id: 5,
    category: "야구",
    name: "BAT야구클럽",
    location: "부산",
    meetingDay: "매주 토요일",
    fee: "월 30,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballa_5.jpg",
  },
  {
    id: 6,
    category: "야구",
    name: "PL풋볼클럽",
    location: "부산",
    meetingDay: "매주 토요일",
    fee: "월 30,000원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballa_6.jpg",
  },
  // 여기에 더 많은 모임 데이터 추가...
];

export const companies = [
  {
    id: 1,
    category: "캠핑",
    name: "글랜비",
    location: "경기도 화성",
    time: "월~일 09:00~18:00",
    fee: "1박 10만원",
    thumbnail: "https://gi.esmplus.com/jjumang/gramb.jpg",
  },
  {
    id: 2,
    category: "캠핑",
    name: "어반티지",
    location: "인천 강화도",
    time: "월/수/금 06:00~14:00",
    fee: "1시간 5만원",
    thumbnail: "https://gi.esmplus.com/jjumang/urban.jpg",
  },
  {
    id: 3,
    category: "캠핑",
    name: "유식물원캠핑장",
    location: "경기도 포천",
    time: "연중무휴",
    fee: "2시간 7만원",
    thumbnail: "https://gi.esmplus.com/jjumang/upalnt.jpg",
  },
  {
    id: 4,
    category: "캠핑",
    name: "채움 카라반",
    location: "경기 가평군",
    time: "화/목 13:00~17:00",
    fee: "1시간 3만원",
    thumbnail: "https://gi.esmplus.com/jjumang/chaeum.jpg",
  },
  {
    id: 5,
    category: "캠핑",
    name: "트라움 글램핑",
    location: "경기 가평군",
    time: "월~목 18:00~24:00",
    fee: "3시간 8만원",
    thumbnail: "https://gi.esmplus.com/jjumang/traum.jpg",
  },
  {
    id: 6,
    category: "캠핑",
    name: "럭셔리 캠핑장",
    location: "서울시 북한산",
    time: "월~목 18:00~24:00",
    fee: "3시간 8만원",
    thumbnail: "https://gi.esmplus.com/jjumang/luxury.jpg",
  },
  {
    id: 1,
    category: "야구",
    name: "엠비피리그",
    location: "서울시 송파구",
    time: "월~금 09:00~18:00",
    fee: "2시간 12만원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballb_1.jpg",
  },
  {
    id: 2,
    category: "야구",
    name: "신길야구장",
    location: "안산 단원구",
    time: "토~일 06:00~24:00",
    fee: "1시간 8만원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballb_2.jpg",
  },
  {
    id: 3,
    category: "야구",
    name: "몽클래스",
    location: "인천시 서구",
    time: "화/목/토",
    fee: "2시간 10만원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballb_3.jpg",
  },
  {
    id: 4,
    category: "야구",
    name: "훼릭스베이스볼",
    location: "대구시 달성구",
    time: "화/목 13:00~17:00",
    fee: "1시간 3만원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballb_4.jpg",
  },
  {
    id: 5,
    category: "야구",
    name: "구리한강파크",
    location: "구리시 토평동",
    time: "수~목 13:00~21:00",
    fee: "3시간 20만원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballb_5.jpg",
  },
  {
    id: 6,
    category: "야구",
    name: "제스트",
    location: "아산시 탕정면",
    time: "월~목 15:00~29:00",
    fee: "2시간 13만원",
    thumbnail: "https://gi.esmplus.com/jjumang/baseballb_6.jpg",
  },
  // 여기에 더 많은 업체 데이터 추가...
];
